### ISSUE TITLE
[e-link][explore][ldf] broken on freme 0.4 and following?

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/e-services#10]
`post /e-link/explore ldf` seems to be broken. The following curl does not work:
```
`curl -X POST "http://api.freme-project.eu/0.4/e-link/explore?resource=http://dbpedia.org/resource/Berlin&endpoint=http://fragments.dbpedia.org/2014/en&endpoint-type=ldf"
```
result:
```
{
  "exception": "eu.freme.broker.exception.InternalServerErrorException",
  "path": "/e-link/explore",
  "message": "Unknown problem. Please contact us.",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1460391260772
}
```

explore sparql still works:
```
curl -X POST "http://api.freme-project.eu/0.4/e-link/explore?resource=http://dbpedia.org/resource/Berlin&endpoint=http://dbpedia.org/sparql&endpoint-type=sparql"
```

**Comment by ArneBinder** [comment]
I un-ignored the JUnit tests, they work (with the mockup endpoint).

**Comment by jnehring** [comment]
**I can reproduce the problem.

Explore sparql endpoint works:

```
curl -X POST "http://api.freme-project.eu/current/e-link/explore?resource=http%3A%2F%2Fdbpedia.org%2Fresource%2FBerlin&endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql&endpoint-type=sparql"
```

I checked the logfiles. There is a NullPointerException and a stack trace:

```
ERROR   2016-04-12 15:47:50,667 [http-nio-8084-exec-2] eu.freme.eservices.elink.api.DataEnricher  - java.lang.NullPointerException
        at java.nio.CharBuffer.wrap(CharBuffer.java:487)
        at com.github.fge.uritemplate.parse.URITemplateParser.parse(URITemplateParser.java:55)
        at com.github.fge.uritemplate.URITemplate.<init>(URITemplate.java:52)
        at org.linkeddatafragments.model.LinkedDataFragment.setTemplate(LinkedDataFragment.java:140)
        at org.linkeddatafragments.model.LinkedDataFragment.hydraParse(LinkedDataFragment.java:85)
        at org.linkeddatafragments.model.LinkedDataFragment.<init>(LinkedDataFragment.java:77)
        at org.linkeddatafragments.model.LinkedDataFragmentFactory.create(LinkedDataFragmentFactory.java:18)
        at org.linkeddatafragments.client.LinkedDataFragmentsClient.getBaseFragment(LinkedDataFragmentsClient.java:60)
        at org.linkeddatafragments.model.LinkedDataFragmentGraph.graphBaseSize(LinkedDataFragmentGraph.java:102)
        at com.hp.hpl.jena.graph.impl.GraphBase.size(GraphBase.java:344)
        at org.linkeaddatafragments.solver.ReorderTransformationLDF.<init>(ReorderTransformationLDF.java:41)
        at org.linkeddatafragments.model.LinkedDataFragmentGraph.<init>(LinkedDataFragmentGraph.java:37)
        at eu.freme.eservices.elink.api.DataEnricher.enrichViaLDFExplore(DataEnricher.java:207)
        at eu.freme.eservices.elink.api.DataEnricher.exploreResource(DataEnricher.java:183)
```

@m1ci any idea whats wrong?

**Comment by m1ci** [comment]
hard to say, no changes has been done in the recent period

**Comment by m1ci** [comment]
I tried to find the issue but without success. 
The issue seems to be between Jena/LDF dependencies in FREME.
Probably something has changed during the migration to the new architecture.

**Comment by jnehring** [comment]
> Probably something has changed during the migration to the new architecture.

The problem happens on FREME live which still runs the old architecture. Sorry milan this is an old bug :)

Does the bug occur on dbpedia only or is the endpoint LDF explore generally broken?

**Comment by m1ci** [comment]
> The problem happens on FREME live which still runs the old architecture. Sorry milan this is an old bug :)

not really, see bellow :)

> Does the bug occur on dbpedia only or is the endpoint LDF explore generally broken?

Very valid question, just checked and this particular LDF endpoint is broken. The LDF explore API is OK.  For example, the ORCID endpoint (http://rv2622.1blu.de:5000/orcid) is working. Here is example:

`curl -X POST --header "Content-Type: application/json" --header "Accept: text/turtle" "http://api.freme-project.eu/0.5/e-link/explore?resource=http%3A%2F%2Forcid.org%2F0000-0001-5000-0736&endpoint=http%3A%2F%2Frv2622.1blu.de%3A5000%2Forcid&endpoint-type=ldf" -v`

**Comment by jnehring** [comment]
When it happens only at DBPedia then I guess the problem lies within DBPedia LDF endpoint and not within our codes. So we can do nothing about it. I leave the issue open so we can test it again in a few weeks. Maybe it solves itself by the next update in DBPedia.

**Comment by jnehring** [comment]
Maybe this will be fixed by updating Jena: https://github.com/freme-project/e-Link/issues/69

**Comment by ArneBinder** [comment]
I can not reproduce thsi anymore, is it fixed? Can we close this?

**Comment by jnehring** [comment]
The error still occurs. Now the CURL (see first comment) produces

```
{
  "exception": "eu.freme.common.exception.BadRequestException",
  "path": "/e-link/explore",
  "message": "Something went wrong when retrieving the content. Please contact the maintainers.",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1468505897979
}
```

I still think that the problem originates from within DBPedia.

**Comment by ArneBinder** [comment]
It is really strange that I get a result if `endpointType` is set to `sparql` (but using the ldf endpoint!): 
```
curl -X POST "http://api-dev.freme-project.eu/current/e-link/explore?resource=http://dbpedia.org/resource/Berlin&endpoint=http://fragments.dbpedia.org/2014/en&endpoint-type=sparql"
```

Btw using endpointType=ldf gives this:
```
INFO    2016-07-18 11:25:08,093 [http-nio-8084-exec-2] eu.freme.bservices.filters.logging.LoggingFilter  - Request: request id=53; uri=/e-link/explore?resource=http://dbpedia.org/resource/Berlin&endpoint=http://fragments.dbpedia.org/2014/en&endpoint-type=ldf; payload=
WARN    2016-07-18 11:25:08,499 [http-nio-8084-exec-2] org.apache.jena.riot  - Only triples or default graph data expected : named graph data ignored
ERROR   2016-07-18 11:25:08,544 [http-nio-8084-exec-2] eu.freme.eservices.elink.api.DataEnricher  - java.lang.NullPointerException
```

especially: **Only triples or default graph data expected : named graph data ignored**
Perhaps this can help in resolving this.

**Comment by jnehring** [comment]
@ArneBinder please do not invest more time on this. We think that this problem is dbpedia specific and the feature is not used by anyone anyways.
